### ISSUE TITLE
Add blank line at the end of all files for syntax highlighting

### ISSUE THREAD

**Issue by aahan** [mattiasgeniar/varnish-3.0-configuration-templates#16]
I think you should try adding a blank line at the end of `.vcl` files when GitHub isn't syntax highlighting them. For e.g., in your repo, this vcl file isn't being syntax-highlighted: <https://github.com/mattiasgeniar/varnish-3.0-configuration-templates/blob/master/production.vcl>

**Comment by mattiasgeniar** [comment]
This seems fixed now.
